# Dependencies
markdown: kramdown
highlighter: rouge

# Gems
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-redirect-from
  - jekyll-seo-tag

# Settings
color: '#fab005'
exclude:
  [
    CNAME,
    README.md,
    NOTES.md,
    LICENSE.md,
    .gitignore,
    package.json,
    _js,
    _scss,
    _images,
    gulpfile.js,
    gulpconfig.js,
    node_modules,
    gemfile,
    Gemfile.lock,
  ]
permalink: /:title/
compress_html:
  clippings: all
  comments: all
dark_theme: false

# Site meta
title: La cuisine de Philly
tagline: "Des recettes au fil des saisons"
description: "Un carnet de recette au fil des saisons, saupoudré d'un peu de diététique, de beaucoup d'amour et de passion"
keywords: "cuisine, recettes, lacuisinedephilly, diététique, sucré, salé, cocktail, patisserie"
url: https://github.com/ptitphilly/ptitphilly.github.io
baseurl: 
assets: /assets
images: /images
image: index-large.jpg
logo: /assets/icons/apple-icon-144x144.png

author:
  name: Philippine Chevreux
  bio: Hello, je suis Philippine l'auteur de ce blog! Bienvenue dans ma cuisine
  image: author
  url: https://ptitphilly.github.io/
  email: philippine.chevreux@gmail.com
  social:
    instagram: https://www.instagram.com/lacuisinedephilly/

version: 2.0.0

# Integrations
# typekit:              fcv7rfe

google_fonts:
  Overpass: 400, 600, 800

# google_analytics_key: UA-37412525-4
# google_site_verification: Z-pc_HPc4XNBz8xg1fgtxO2MSIYLirZc2jWTNq0bJyM

# Content
excerpt_separator: <!-- Read more -->

navigation:
  Accueil: / # Home
  # Articles: about/ # TODO
  #Télécharger: # TODO

collections:
  recipes:
    output: true

defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
      lang: fr
      permalink: /posts/:title/
  - scope:
      path: ''
      type: recipes
    values:
      layout: recipe
      lang: fr
      permalink: /recipes/:title/
